# TODO CHECK THIS PIPELINE ACTUALLY WORKS

# Change so it runs on every branch, so they need to change this
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: nodejs
    displayName: "Build and test Javascript"
    steps:
      - task: NodeTool@0
        displayName: "Install NodeJS + NPM"
        inputs:
          versionSpec: "16.x"

      - script: npm install
        displayName: npm install
        workingDirectory: "DotnetTemplate.Web"

      - script: npm run build
        displayName: npm build
        workingDirectory: "DotnetTemplate.Web"

      - script: npm run test
        displayName: npm build
        workingDirectory: "DotnetTemplate.Web"

      - script: npm run lint
        displayName: npm lint
        workingDirectory: "DotnetTemplate.Web"

  - job: dotnet
    displayName: "Build and test .NET"
    steps:
      - task: UseDotNet@2
        displayName: "Install .NET SDK"
        inputs:
          version: "7.0.x"

      - script: dotnet build
        displayName: dotnet build

      - script: dotnet test
        displayName: dotnet test